name: crmMobileUi
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_speed_dial: ^7.0.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.1
  provider: ^6.1.5+1
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^6.0.0
  http: ^1.5.0
  intl: ^0.19.0
  dio: ^5.9.0
  msal_auth: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/config.json
    - assets/images/
    - assets/images/sidemenu/
    - assets/msal_config.json
